### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rijnhard** [Darkhogg/enhanced-event-emitter#1]
in the emit https://github.com/Darkhogg/enhanced-event-emitter/blob/master/src/eee.js#L141

Is there a reason why you resort the listeners? Event Emitters are pretty high traffic so it's one the few places where micro-optimizations are actually warranted, the thinner the emit can be the better

**Comment by Darkhogg** [comment]
They are re-sorted because when emitting multiple events at the same time the priority is respected on the listeners as a whole, not separately for each of the emitted events.

The only solutions would be:
 1. Change the behavior so each event is emitted independently (no sorting required as they are sorted in `on`)
 2. Sort only when emitting multiple events, as with a single one it's not necessary
 3. Implement some sort of caching for multi-emitting so no sorting is necessary

3 is overkill; I'm not sure if the behavior of 1 is actually interesting, and 2 seems reasonable and might include extra optimizations for this particular case.

I might come back and do this if I have time this week, the code there looks like it needs a bit of cleanup too.

**Comment by rijnhard** [comment]
If I feel like it I may give it a crack too, maybe use some of the
comparable libraries for inspiration. These kinds of silly changes can be
quite fun

**Comment by rijnhard** [comment]
On another note, I don't think the library needs `bluebird` as a dependency, don't get me wrong I like it too, but `await` will implicitly wrap and unwrap a non-promise so we don't need to cast to a promise. 

https://github.com/Darkhogg/enhanced-event-emitter/blob/master/src/eee.js#L154

besides that `Bluebird.cast` is has been deprecated for a while and you could just use es6 `Promise.resolve`, but regardless it's not needed because of the await semantics.

**Comment by Darkhogg** [comment]
This library is older than native async/await, and I haven't really looked at it for a while. I'll take a look at it as a whole later this week.

Also, as this was a question that was already answered, I'm going to close the ticket. If you want to propose something specific, even if it was talked here, please open a different issue.

Thank you for your comments, though, it's nice to have someone looking at this. 😄
